# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Sonu Kumar
title: Senior Android Developer | Software Engineer
email: skbhati199@gmail.com
# email_title: Email (Email title override)
phone: 9810659036
# phone_title: Phone (Phone title override)
website: https://fluper.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: SonuKum02900474
github_username:  skbhati199
stackoverflow_username: "00000001"
facebook_username: skbhati199
instagram_username: skbhati1992
linkedin_username: sonu-kumar-9810659036

# Additional icon links
additional_links:
- title: Github
  icon: fab fa-github
  url: https://github.com/skbhati199
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Talented Android Developer with over 7+ years of software and web services development experience in a broad range of industries, including city management, traffic management, 
  toll system management, PWA, Flutter, Music App, Video Calling app, Short Video App, music App, and mobile gaming. Solid understanding of full mobile and software development 
  life cycles, UIX, web analytics, changing web standards, and Application methodologies. Dedicated to continuously developing, implementing, and adopting new technologies to 
  maximize development efficiency and produce innovative applications..

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TelioEV
        link: https//www.telioev.com
        link_text: Details
        quote: >
          Telio EV Charging App
        description: | # this will include new lines to allow paragraphs
          Developed Telio EV Charging for sustainable mobility infrastructure,
      - layout: left
        title: Feguu And Owner
        link: https//www.fluper.com
        link_text: Details
        quote: >
          Feguu And Owner
        description: | # this will include new lines to allow paragraphs
          Development application like if customer want services like beauty related can do booking,
      - layout: left
        title: Fudiis Food Services
        link: https//www.fluper.com
        link_text: Details
        quote: >
          Fudiis Food Services
        description: | # this will include new lines to allow paragraphs
          Delivery service food and restaurant services
      - layout: left
        title: DynDish Restaurant Services
        link: https//www.fluper.com
        link_text: Details
        quote: >
          DynDish Restaurant Services
        description: | # this will include new lines to allow paragraphs
          It's provide food services online table side, delivery, pickup and curbside
      - layout: left
        title: StyleOak
        link: https//www.fluper.com
        link_text: Details
        quote: >
          StyleOak
        description: | # this will include new lines to allow paragraphs
          E COMMERCE ANDROID APP
      - layout: left
        title: E-commerce StyleKart Android
        link: https//www.fluper.com
        link_text: Details
        quote: >
          E-commerce StyleKart Android
        description: | # this will include new lines to allow paragraphs
          E COMMERCE ANDROID APP
      - layout: left
        title: Quick Serve
        link: https//www.fluper.com
        link_text: Details
        quote: >
          Quick Serve
        description: | # this will include new lines to allow paragraphs
          Like Freelance or urban clap Android App,
      - layout: left
        title: Music ANDROID APPLICATION
        link: https//www.fluper.com
        link_text: Details
        quote: >
          Music ANDROID APPLICATION
        description: | # this will include new lines to allow paragraphs
          Maintenance for some issues fix accordingly to Pie

      - layout: left
        title: Doctor On Demand
        link: https//www.fluper.com
        link_text: Details
        quote: >
          Doctor On Demand
        description: | # this will include new lines to allow paragraphs
          Doctor and Patient consultant Android Application

      - layout: left
        title: E-commerce DEELZAT ANDROID
        link: https//www.fluper.com
        link_text: Details
        quote: >
          E-commerce DEELZAT ANDROID
        description: | # this will include new lines to allow paragraphs
          Same Letgo Android app and Quickr

      - layout: left
        title: Highway Saathi OBU
        link: https//www.fluper.com
        link_text: Details
        quote: >
          EHighway Saathi OBU
        description: | # this will include new lines to allow paragraphs
          HIGHWAY SAATHI OBU DEVICE

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Infoskills Technology Pvt Ltd
        sub_title: Android Developer
        caption: Date Range (eg. May 2022 - present)
        link: https//www.infoskillstechnology.com
        quote: >
          React Native/Flutter/Android/iOS Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features
      - layout: right
        title: Fluper Limited
        sub_title: Android Developer
        caption: Date Range (eg. Feb 2020 - Apr 2022)
        link: https//www.fluper.com
        quote: >
          Mobile Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features

      - layout: right
        title: Fluper Limited
        sub_title: Android Developer
        caption: 2 Years 2 Months (Feb 2020 - present)
        link: https//www.fluper.com
        quote: >
          Mobile Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features


      - layout: right
        title: Hire Indians InfoTech Pvt Ltd
        sub_title: Android Developer
        caption: 6 Months ( Feb 2019 - Jan 2020)
        link: https//www.hireindians.com
        quote: >
          Mobile Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features


      - layout: right
        title: Metro Infrasys Private Limited
        sub_title: Android Developer
        caption: 3 Years 3 Month (May 2016 - July 2019)
        link: https//www.metroinfrasys.com
        quote: >
          Mobile Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features


      - layout: right
        title: Zebrogs Technologies
        sub_title: Android Developer
        caption: 9 Months (Aug 2015 - Apr 2016)
        link: https//www.fluper.com
        quote: >
          Mobile Apps Developement 
        description: | # this will include new lines to allow paragraphs
          Application Development with Team + design + code + features
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: NIET College
        sub_title: MCA, Computer Science
        caption: 2013 - 2015
        quote: >
          Database, OS, JAVA, C, C++, .Net, etc
        description: | # this will include new lines to allow paragraphs
          Computer Sciencce
      - layout: top-right
        title: IP College
        sub_title: BCA, Computer Science
        caption: 2010 - 2013
        quote: >
          C, C++. SQL
        description: | # this will include new lines to allow paragraphs
          Computer Sciencce
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Talented Android Developer with over 6.5+ years of software and web services development experience in a broad range of industries, including city management, traffic management, 
      toll system management, PWA, Flutter, Music App, Video Calling app, Short Video App, music App, and mobile gaming. Solid understanding of full mobile and software development 
      life cycles, UIX, web analytics, changing web standards, and Application methodologies. Dedicated to continuously developing, implementing, and adopting new technologies to 
      maximize development efficiency and produce innovative applications..

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
